import{S as L,a as b,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const p=document.querySelector(".gallery"),m=document.getElementById("loader"),v=new L(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){const r=e.map(({webformatURL:a,largeImageURL:s,tags:t,likes:o,views:i,comments:y,downloads:h})=>`
       <li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${a}" alt="${t}" />
            <div class="info">
              <p><span class="label">Likes</span><span class="value">${o}</span></p>
              <p><span class="label">Views</span><span class="value">${i}</span></p>
              <p><span class="label">Comments</span><span class="value">${y}</span></p>
              <p><span class="label">Downloads</span><span class="value">${h}</span></p>
            </div>
          </a>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),v.refresh()}function w(){p.innerHTML=""}function S(){m.classList.remove("is-hidden")}function q(){m.classList.add("is-hidden")}function B(){const e=document.querySelector(".load-more");e&&(e.style.display="block")}function u(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const M="https://pixabay.com/api/",E="49539042-7a7029324b91a0a3f345412f4";async function g(e,r=1){const a={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return S(),(await b.get(M,{params:a})).data}catch{throw new Error("Failed to fetch images")}finally{q()}}const O=document.querySelector(".form"),P=document.querySelector(".load-more");document.addEventListener("DOMContentLoaded",()=>{u()});let c="",n=1,d=0;O.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-text"].value.trim(),n=1,!c){l.error({message:"Empty input, enter a search value!",position:"topRight"});return}w(),u();try{const r=await g(c,n),{hits:a,totalHits:s}=r;if(a.length===0){l.error({message:"Sorry, no images match your query. Try again!",position:"topRight"});return}f(a),d=Math.ceil(s/15),n<d&&a.length===15&&B()}catch{l.error({message:"Something went wrong",position:"topRight"})}});P.addEventListener("click",async()=>{if(c){n+=1;try{const e=await g(c,n);f(e.hits),setTimeout(()=>{R()},150),(e.hits.length<15||n>=d)&&(u(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({message:"Failed to load more images",position:"topRight"})}}});function R(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
